---
channel: stable
addons:
  adguard:
    repository: botts7/addon-adguard-home
    target: adguard
    image: ghcr.io/botts7/adguard/{arch}
  aircast:
    repository: botts7/addon-aircast
    target: aircast
    image: ghcr.io/botts7/aircast/{arch}
  airsonos:
    repository: botts7/addon-airsonos
    target: airsonos
    image: ghcr.io/botts7/airsonos/{arch}
  appdaemon:
    repository: botts7/addon-appdaemon
    target: appdaemon
    image: ghcr.io/botts7/appdaemon/{arch}
  bitwarden:
    repository: botts7/addon-bitwarden
    target: bitwarden
    image: ghcr.io/botts7/bitwarden/{arch}
  bookstack:
    repository: botts7/addon-bookstack
    target: bookstack
    image: ghcr.io/botts7/bookstack/{arch}
  chrony:
    repository: botts7/addon-chrony
    target: chrony
    image: ghcr.io/botts7/chrony/{arch}
  esphome:
    repository: esphome/hassio
    target: esphome
    image: esphome/esphome-hassio-{arch}
  example:
    repository: botts7/addon-example
    target: example
    image: ghcr.io/botts7/example/{arch}
  foldingathome:
    repository: botts7/addon-foldingathome
    target: foldingathome
    image: ghcr.io/botts7/foldingathome/{arch}
  ftp:
    repository: botts7/addon-ftp
    target: ftp
    image: ghcr.io/botts7/ftp/{arch}
  glances:
    repository: botts7/addon-glances
    target: glances
    image: ghcr.io/botts7/glances/{arch}
  grafana:
    repository: botts7/addon-grafana
    target: grafana
    image: ghcr.io/botts7/grafana/{arch}
  grocy:
    repository: botts7/addon-grocy
    target: grocy
    image: ghcr.io/botts7/grocy/{arch}
  home-panel:
    repository: botts7/addon-home-panel
    target: home-panel
    image: ghcr.io/botts7/home-panel/{arch}
  influxdb:
    repository: botts7/addon-influxdb
    target: influxdb
    image: ghcr.io/botts7/influxdb/{arch}
  jupyterlab:
    repository: botts7/addon-jupyterlab
    target: jupyterlab
    image: ghcr.io/botts7/jupyterlab/{arch}
  log-viewer:
    repository: botts7/addon-log-viewer
    target: log-viewer
    image: ghcr.io/botts7/log-viewer/{arch}
  matrix:
    repository: botts7/addon-matrix
    target: matrix
    image: ghcr.io/botts7/matrix/{arch}
  motioneye:
    repository: botts7/addon-motioneye
    target: motioneye
    image: ghcr.io/botts7/motioneye/{arch}
  node-red:
    repository: botts7/addon-node-red
    target: node-red
    image: ghcr.io/botts7/node-red/{arch}
  nginxproxymanager:
    repository: botts7/addon-nginx-proxy-manager
    target: proxy-manager
    image: ghcr.io/botts7/nginxproxymanager/{arch}
  nut:
    repository: botts7/addon-nut
    target: nut
    image: ghcr.io/botts7/nut/{arch}
  phpmyadmin:
    repository: botts7/addon-phpmyadmin
    target: phpmyadmin
    image: ghcr.io/botts7/phpmyadmin/{arch}
  plex:
    repository: botts7/addon-plex
    target: plex
    image: ghcr.io/botts7/plex/{arch}
  portainer:
    repository: botts7/addon-portainer
    target: portainer
    image: ghcr.io/botts7/portainer/{arch}
  spotify:
    repository: botts7/addon-spotify-connect
    target: spotify
    image: ghcr.io/botts7/spotify/{arch}
  tailscale:
    repository: botts7/addon-tailscale
    target: tailscale
    image: ghcr.io/botts7/tailscale/{arch}
  tasmoadmin:
    repository: botts7/addon-tasmoadmin
    target: tasmoadmin
    image: ghcr.io/botts7/tasmoadmin/{arch}
  tautulli:
    repository: botts7/addon-tautulli
    target: tautulli
    image: ghcr.io/botts7/tautulli/{arch}
  thelounge:
    repository: botts7/addon-thelounge
    target: thelounge
    image: ghcr.io/botts7/thelounge/{arch}
  ssh:
    repository: botts7/addon-ssh
    target: ssh
    image: ghcr.io/botts7/ssh/{arch}
  sqlite-web:
    repository: botts7/addon-sqlite-web
    target: sqlite-web
    image: ghcr.io/botts7/sqlite-web/{arch}
  tor:
    repository: botts7/addon-tor
    target: tor
    image: ghcr.io/botts7/tor/{arch}
  traccar:
    repository: botts7/addon-traccar
    target: traccar
    image: ghcr.io/botts7/traccar/{arch}
  unifi:
    repository: botts7/addon-unifi
    target: unifi
    image: ghcr.io/botts7/unifi/{arch}
  vscode:
    repository: botts7/addon-vscode
    target: vscode
    image: ghcr.io/botts7/vscode/{arch}
  wireguard:
    repository: botts7/addon-wireguard
    target: wireguard
    image: ghcr.io/botts7/wireguard/{arch}
  zerotier:
    repository: botts7/addon-zerotier
    target: zerotier
    image: ghcr.io/botts7/zerotier/{arch}
  zwavejs2mqtt:
    repository: botts7/addon-zwavejs2mqtt
    target: zwavejs2mqtt
    image: ghcr.io/botts7/zwavejs2mqtt/{arch}
